server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo2_test?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    show-aql: true
    database: mysql

management:
  endpoint:
    health:
      enabled: true
      show-details: always