spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo2?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    show-aql: true
    database: mysql

server:
  port: 8083
management:
  endpoint:
    health:
      enabled: true
      show-details: always