spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo2_product?characterEncoding=utf-8
    username: root
    password: 123456
  application:
    name: product-service
  jpa:
    show-aql: true
    database: mysql
server:
  port: 8081
management:
  endpoint:
    health:
      enabled: true
      show-details: always
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/