server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo2?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    show-aql: true
    database: mysql

zuul:
  routes:
    product:
      url: http://localhost:8081/products
      path: /products/**
    order:
      url: http://localhost:8082/orders
      path: /orders/**
    user:
      url: http://localhost:8083/users
      path: /users/**

management:
  endpoints:
    web:
      exposure:
        include: routes,filters
