spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo2_order?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    show-aql: true
    database: mysql
  application:
    name: order-service
server:
  port: 8082
management:
  endpoint:
    health:
      enabled: true
      show-details: always
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/