pipeline {
    agent any

    stages {
        stage('Test') {
            steps {
                sh './gradlew test'
            }
        }
        stage('CheckStyle') {
            steps {
                sh './gradlew checkstyleMain'
            }
        }
    }
}